services:
  # .NET Web API приложение
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/WebApplication3.db
    volumes:
      - ./WebApplication3/WebApplication3.db:/app/WebApplication3.db
    restart: unless-stopped 